title: relx Documentation
description: Modern C++23 library for building and executing SQL queries with compile-time type safety
baseurl: "/relx"  # Replace with your actual repo name if different
url: "https://yourusername.github.io"  # Replace with your GitHub username

# Jekyll configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Theme - using Cayman for better documentation appearance
remote_theme: pages-themes/cayman@v0.2.0

# Navigation
header_pages:
  - schema-definition.md
  - query-building.md
  - result-parsing.md
  - error-handling.md
  - advanced-examples.md
  - performance.md
  - development.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# GitHub metadata
repository: yourusername/relx

# SEO and social
author: relx Team
twitter:
  username: # Add if you have one
  card: summary

logo: # Add a logo path if you have one

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - api/

# Collections for better organization
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default" 